messages:
  # Все сообщения кроме префикса поддерживают kyori MiniMessage - https://docs.advntr.dev/minimessage/format.html
  prefix: §7[§6GriefMod§7]§f
  # Сообщение над хотбаром оповещающее игрока о том что у него грифмод
  disabled-actionbar: <color:#FF0000>Вы не можете этого сделать!
  grief-change:
    # Сообщение игроку когда у него снимается грифмод
    enabled-message: <color:#00FF00>Теперь вам доступны новые возможности!
    # Сообщение игроку когда на него накладывается грифмод
    disabled-message: <color:#FF3333>У вас забрали некоторые возможности..

# Время которое необходимо наиграть для снятия грифмода (Целое число в минутах)
# 60 - 1 час
# 1440 - 1 день
grief-disable-minutes: 1440
# Время раз в которое проверяется наигранное время у игроков для снятия грифмода (Целое число в минутах)
grief-auto-check: 1

# Указываются материалы в верхнем регистре, список - https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Либо F3+H - навестись на предмет и взять текст после minecraft: и записать его в верхнем регистре
grief-disabled:
  # Отключить удары по игрокам
  disable-pvp: true
  # Блоки которые нельзя ставить в грифмоде
  place:
    - TNT
    - RESPAWN_ANCHOR
    - WITHER_SKELETON_SKULL
  # Блоки которые нельзя ломать в грифмоде
  destroy: []
  interact:
    # Блоки/Предметы которые нельзя использовать в грифмоде
    use:
      - FLINT_AND_STEEL
      - FIRE_CHARGE
      - END_CRYSTAL
      - LAVA_BUCKET
    bucket:
      empty:
        # true - запретить разливание лавы в грифмоде false - разрешить разливание лавы в грифмоде
        lava: true
        # true - запретить разливание воды в грифмоде false - разрешить разливание воды в грифмоде
        water: false